### ISSUE TITLE
Information about the code and possibility of version with new GUI/without GUI.

### ISSUE THREAD

**Issue by deep-man-yy** [open-deepnude/open-deepnude#11]
Greetings to all. I have been playing with the code and I would like to share everything I have discovered and understood about how the program works, I think I have what it takes to create a version with a new and customizable GUI as well as a version without GUI (Terminal only) in the future.

I have no experience with Python (but with several other languages) so it is possible that I am wrong in some things.

1. `run.py` is the file that works as start to photo processing and is used by `main.py`. `run.py` only has the functions to start the process so running this file alone would do absolutely nothing but it is the ideal place to start to understand what should be done to separate it from the official GUI.
2. `main.py` is the GUI. Executing this file correctly will open the GUI of the program (that we all know as DeepNude.exe). In this file you can edit things like the name of the program, the logo, images and delete all the code related to the "Premium" version. When you select a photo and click on "Transform" a function is called inside `run.py`.
3. For now it is not possible to execute correctly  the file `main.py` since the `QtImageCropper` module is **missing**. `QtImageCropper` seems to be a module created by the DeepNude Developer and its code is not found in Google (at least I could not find it), it is a Widget for PyQt5 in charge of indicating the limits of the photo for its clipping and saving the final result after its processing. The only solutions I see for this is to find the location of the code of this module and decompile it or create a new version and adapt `main.py`
4. Using the version of Torch that uses GPU and modifying the file `textsubline.py` it is possible to use the **processing by GPU** instead of CPU. The line that I modified is: `self.gpu_ids = [0]` (But this may vary)

---

Here I only modified the texts and removed all the code that had to do with the "Premium" system:

![](https://i.imgur.com/sfhOre2.png)

In the meantime I will try to make a new version that uses CEF as GUI instead of PyQt5, although I do not promise anything.

---

**Progress 1:**

After a few hours I managed to execute the file `run.py` without problems and I can also **process photos with GPU** instead of CPU. To avoid the problem of `QtImageCropper` I have implemented C.E.F. (Chromium) and create a placeholder GUI. More information about this in the future.

https://i.imgur.com/1DhofVC.gif

For now I have only noticed an increase in the processing speed, in terms of quality I have not noticed any improvements.

---

My "work environment":

- Windows 10
- RTX 2070
- Python 3.6.8
- CUDA 9
- opencv-python==4.1.0.25
- numpy==1.16.0
- rsa==4.0
- pyqt5==5.12.3
- cefpython3==66.0
- `https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl`
- `https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl`

**Comment by najisunade** [comment]
@deep-man-yy Hi. You can share your code ?

**Comment by deep-man-yy** [comment]
> @deep-man-yy Hi. You can share your code ?

As soon as I have something important and stable I will create a fork of the repository with all the changes, right now I am experimenting and discovering new things.

**Comment by najisunade** [comment]
@deep-man-yy Thank a lot. Your awesome. >_<

**Comment by deeppppp** [comment]
"To solve it, someone needs to find out where that code is and decompile it or create another version and adapt main.py to the new one."

I think that's the priority item right now, and will get the application to function as the original.
After that improvements will come, 

The instructions mentioned in this thread should go to the 'README.md' file of the project in Github after they are cleaned up :)

Some additional info:
On Windows:
Use Python 3.6x because of the .pyd files are for version 3.6; running under Python 3.7 will give you DLL errors for example.

libsqld.py is missing from github, create it and add these lines:
def add(a, b, c):
	return a

preferences.json is missing from github, create it and add:
{"init": "yes", "library": "yes", "email": "", "transform": "yes"}

pyqtlib directory with the data files is missing:
cm.lib 
mm.lib 
mn.lib 
are large data files that can be found on the Internet, should be added to github.

qtbin directory is missing
This contains images to be included in the GUI:
false.png
instructiongui.png
invitation.png
loading.gif
logo.png
premium.jpg
true.pung

can be found on the Internet

---
Install Python 3.6
upgrade PIP:
python.exe -m pip install --upgrade pip

install dependencies:
pip install opencv-python
pip install pillow

(torch and torchvision)
pip3 install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl
pip3 install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl

pip install rsa
pip install pyQt5

---
execute application
python main.py

----
as mentioned here, this will throw an error because QtImageCropper is missing.
you can comment out the line #13 in main.py and the application will now open the GUI, allow for image selection and then it will try to use the functions of QtImageCropper  module and crash.

**Comment by deep-man-yy** [comment]
@deeppppp Thank you! And yes, everything you said is correct, I updated the post with more ordered information as well as an example of the processing without using the official GUI.

**Comment by stacklikemind** [comment]
https://github.com/deepinstruction/deepnude_official

**Comment by deeppppp** [comment]
Few comments on the deepnude_official github:
Awesome that the algorithm was published !
Now this can be improved on.

What was not published is a Graphical User Interface, something that @deep-man-yy was working on.
It would be great if he can still complete this and publish it ;)

Why is a User Interface still needed?

1) The input image has to be 512px by 512px otherwise the algorithm will fail. 
That's why a cropping function is important.

Until the algorithm can handle dynamic image width / height a method to crop to 512x512 is needed.

2) The main.py function from deepnude_official is hardcoded to have input.png as input.
an easy fix would be to allow a CLI input parameter for the <input> and <output> file names.

But a GUI function to select the input file, show the result and then provide the option to save the output file is a much more user friendly way to do this.

-----

For those wondering how to remove the watermark from the deepnude_official github:
in nude_to_watermark.py file add this extra line at position line #9:
	return nude;

----

For those running into the input image not working because it's not 512px by 512px in size issue:

1) open up an image editor like "paint"
2) resize the input image so that the largest of width / height is 512px and the other is equal or less than 512px.
3) select the resized image and copy to clipboard
4) create a new blank image of size 512px by 512px
5) copy from clipboard your resized input image and place in the center
6) save the combined image to disk as 'input.png'

**Comment by deep-man-yy** [comment]
> https://github.com/deepinstruction/deepnude_official

This will make things much easier, thanks for sharing!

As @deeppppp has explained, the deepnude_official repository contains a much cleaner version of the code but does not have a graphical user interface. Right now I am modifying the deepnude_official code to work as a CLI and maybe later create a friendly graphical user interface with Electron that uses the CLI.

**Comment by wisp101** [comment]
I'm pretty sure that the QtImageCropper is just a python port of the library [here](https://github.com/dimkanovikov/ImageCropper). I'm trying to create a binding right now to see if it works

**Comment by deep-man-yy** [comment]
> I'm pretty sure that the QtImageCropper is just a python port of the library [here](https://github.com/dimkanovikov/ImageCropper). I'm trying to create a binding right now to see if it works

It is very similar but it is not the same, it should not be so difficult to create an implementation even based on that library but I have no idea of PyQt or knowledge about Python so I hope you can do it :)

**Comment by wuya666** [comment]
> > I'm pretty sure that the QtImageCropper is just a python port of the library [here](https://github.com/dimkanovikov/ImageCropper). I'm trying to create a binding right now to see if it works
> 
> It is very similar but it is not the same, it should not be so difficult to create an implementation even based on that library but I have no idea of PyQt or knowledge about Python so I hope you can do it :)

Hmm, just a thought, why do you even need to implement the image cropping thing in Python. As long as the backend engine (the CLI version) works, you can just implement a frontend with, say, nodejs and do the image upload and cropping there, and then pass the cropped image to the CLI to do the transformation, then load and show the transformed image back to the frontend interface, that way you can implement the frontend UI with whatever language and framework you like.

**Comment by deep-man-yy** [comment]
@wuya666 That's exactly what I'm doing, in fact as I said in a comment I'm developing the GUI with Electron. The `QtImageCropper` was just a" curiosity "I never intended to do since I prefer to make an improved GUI in JavaScript. Right now I have a functional CLI version (but without a cropping system), and I just need to make the GUI and I would have a fully functional and open-source version. I do it in my free time so it's possible that I take a little longer.

**Comment by victorca25** [comment]
@wuya666 you need the image cropping because images need to be loaded on VRAM and run through the network. If large images are not cropped, you will get a “CUDA out of memory” error. pix2pixHD (the original network that was the base for this one) needs a lot of memory.

**Comment by wuya666** [comment]
> @wuya666 you need the image cropping because images need to be loaded on VRAM and run through the network. If large images are not cropped, you will get a “CUDA out of memory” error. pix2pixHD (the original network that was the base for this one) needs a lot of memory.

@victorca25 hmm, I never said you don't need the image cropped, just that you don't need to implement the image cropping in Python, the Python part can be implemented as a backend engine, which gets images from the frontend and return the processed results back. Of course you may (and most likely should) implement a image size check on the backend to reject over-sized images.

Currently I'm also playing around with the code from the original author on my own fork of it

https://github.com/wuya666/deepnude_official

I'm thinking about making it into a tornado-based web service module or something, right now I'm testing with various formats and sizes of images to see how it handles different type of pics.

**Comment by deep-man-yy** [comment]
I think I have a prototype:
https://i.imgur.com/Gj5n2ox.gif

Soon everything will be in:
https://github.com/deep-man-yy/easydeepnude

**Comment by deep-man-yy** [comment]
The thread will continue in:
#14
