### ISSUE TITLE
I tried to compile it show No module named 'QtImageCropper'

### ISSUE THREAD

**Issue by deeppppp** [open-deepnude/open-deepnude#8]
python main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from QtImageCropper import QtImageCropper
ModuleNotFoundError: No module named 'QtImageCropper'

**Comment by najisunade** [comment]
I think main.py is not main function, you will see run.py and fix it.

**Comment by deeppppp** [comment]
to me it looks like main.py is the input GUI to add an image and start the processing of it.
it allows to choose a file from disk to load and then
part of this input GUI is cropping the image to the correct size.

but I could be wrong, it's hard for me to see the execution path,...

run.py has it's own issue with 

python run.py
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import libsqla, libsqlb, libsqlc, libsqld
ModuleNotFoundError: No module named 'libsqla'


that's why I started main.py and got a lot further (when I comment out the "from QtImageCropper import QtImageCropper" line)
it shows the GUI, allows for image selection from disk, but then fails.

**Comment by najisunade** [comment]
@deeppppp I saw some file cant decompile eg. libsqla.cp36-win_amd64.pyd may be decompile to libsqla.py same shadow.cp36-win_amd64.pyd to shadow.py

**Comment by deep-man-yy** [comment]
I have been playing a bit with the code, I have no experience using Python (but other programming languages) and this is what I found:

1. `run.py` seems to be the entry to photo training or a similar process however it only contains some functions and not something that can be used to enter commands/input.
2. For the error about the libraries **"libsqla, libsqlb, libsqlc, libsqld"** to disappear you need to add the file `_ctypes.pyd` (You can find it in the full/compiled/cracked version). However it is possible that you get other errors related to other libraries (torch, numpy, etc), I have not continued with this because as I said in the first point does not seem to get anything with that file for now.
3. What interests me most right now is to make the `main.py` file work using torch in **GPU (CUDA)** instead of CPU. I have already managed to install the libraries and when opening `main.py` the program's GUI opens, the only problem is that to achieve this I had to comment the line: `from QtImageCropper import QtImageCropper` **_QtImageCropper_** as its name suggests it seems to be a PyQt5 Widget created by the DeepNude developer, I could not find anything similar in Google, without that widget the box that allows you to crop the images and save them does not work (So the program crashes when a photo is selected). To solve it, someone needs to find out where that code is and decompile it or create another version and adapt `main.py` to the new one.

That's all I have so far, if a solution is found to QtImageCropper it is possible that the GPU can be used and accelerate and/or improve the quality of the transformation.

**Comment by stacklikemind** [comment]
https://github.com/deepinstruction/deepnude_official

**Comment by xXmeme-machineXx** [comment]
Not intended to run this program as GUI, if you want to use it use as CLI
